---
title: "Fine Annotation of CD4 and CD8 T Cells using ProjecTILs"
author: A. Mihaylov <aleksandar.mihaylov@epfl.ch>
---

# Downloading Annotated Dataset

```{r downloading_processed_dataset}
ds_name <- "SalasA_2023_GSE214695"
home.path <- file.path(getwd(), ds_name)
output_data_path <- file.path(home.path, "output")

size <- "whole" # "light" or "whole"

# cmc stands for colonic mucosa cells
cmc <- readRDS(file.path(output_data_path, paste0(ds_name, sprintf("_annotated_%s.rds", size))))
```

# Classification

## Classification of CD4 T and CD8 T cells

```{r seurat_objects_creation}
# Loading functions
source("Rutils/functions.R")

ref_cd4 <- ProjecTILs::get.reference.maps(collection = "human", 
                                          reference = "CD4")[["human"]][["CD4"]]
ref_cd8 <- ProjecTILs::get.reference.maps(collection = "human", 
                                          reference = "CD8")[["human"]][["CD8"]]

cd4_gated_cells <- cell_type_classification(cmc, cell_type = "CD4T", ref_map = ref_cd4)
cd4_manual_cells <- cell_type_classification(cmc, cell_type = "CD4T", ref_map = ref_cd4,
                                             ident_col = "manual_annotation",
                                             filter.cells = FALSE)
cd8_gated_cells <- cell_type_classification(cmc, cell_type = "CD8T", ref_map = ref_cd8)
cd8_manual_cells <- cell_type_classification(cmc, cell_type = "CD8T", ref_map = ref_cd8,
                                             ident_col = "manual_annotation",
                                             filter.cells = FALSE)
```

## Visualization 

Let us first visualize the new ProjecTILs 

```{r umap_visualization}
Seurat::DimPlot(cd4_gated_cells, reduction = "umap", group.by = "functional.cluster", 
                label = FALSE) + ggplot2::ggtitle("Gated CD4 T Cells")

Seurat::DimPlot(cd4_manual_cells, reduction = "umap", group.by = "functional.cluster", 
                label = FALSE) + ggplot2::ggtitle("Manual CD4 T Cells")

Seurat::DimPlot(cd8_gated_cells, reduction = "umap", group.by = "functional.cluster", 
                label = FALSE) + ggplot2::ggtitle("Gated CD8 T Cells")

Seurat::DimPlot(cd8_manual_cells, reduction = "umap", group.by = "functional.cluster", 
                label = FALSE) + ggplot2::ggtitle("Manual CD8 T Cells")
```

In addition, let us see how many cells there are per subtype.

```{r cell_subtype_counts}
cd4_gated_table <- table(cd4_gated_cells$functional.cluster)
knitr::kable(cd4_gated_table, col.names = c("Cell Type", "Counts"), caption = "Gated CD4 T Cells")

cd4_manual_table <- table(cd4_manual_cells$functional.cluster)
knitr::kable(cd4_manual_table, col.names = c("Cell Type", "Counts"), caption = "Manual CD4 T Cells")

cd8_gated_table <- table(cd8_gated_cells$functional.cluster)
knitr::kable(cd8_gated_table, col.names = c("Cell Type", "Counts"), caption = "Gated CD8 T Cells")

cd8_manual_table <- table(cd8_manual_cells$functional.cluster)
knitr::kable(cd8_manual_table, col.names = c("Cell Type", "Counts"), caption = "Manual CD8 T Cells")
```

## Saving Classification Output

```{r saving_classification_output}
saveRDS(cd4_gated_cells, 
        file.path(output_data_path,paste0(ds_name,sprintf("_cd4_gated_%s.rds", size))))
saveRDS(cd4_manual_cells, 
        file.path(output_data_path,paste0(ds_name,sprintf("_cd4_manual_%s.rds", size))))
saveRDS(cd8_gated_cells, 
        file.path(output_data_path,paste0(ds_name,sprintf("_cd8_gated_%s.rds", size))))
saveRDS(cd8_manual_cells, 
        file.path(output_data_path,paste0(ds_name,sprintf("_cd8_manual_%s.rds", size))))
```

# Updating Initial Seurat Object

## Adding New Metadata Columns

```{r adding_meta_columns}
cd4_meta <- cd4_gated_cells@meta.data[, "functional.cluster", drop = FALSE]
cd8_meta <- cd8_gated_cells@meta.data[, "functional.cluster", drop = FALSE]

cmc$fine.annotation.gated <- cmc$scGate_multi 

cmc@meta.data[rownames(cd4_meta), "fine.annotation.gated"] <- cd4_meta
cmc@meta.data[rownames(cd8_meta), "fine.annotation.gated"] <- cd8_meta

#-------------------
cd4_meta <- cd4_manual_cells@meta.data[, "functional.cluster", drop = FALSE]
cd8_meta <- cd8_manual_cells@meta.data[, "functional.cluster", drop = FALSE]

cmc$fine.annotation.manual <- cmc$manual_annotation 

cmc@meta.data[rownames(cd4_meta), "fine.annotation.manual"] <- cd4_meta
cmc@meta.data[rownames(cd8_meta), "fine.annotation.manual"] <- cd8_meta

```

## Saving Updated Seurat Objet

```{r saving_updated_object}
saveRDS(cmc, file.path(output_data_path,paste0(ds_name,sprintf("_finely_annotated_%s.rds", size))))
```


